"""
Shared constants for the trading system
Consolidates commonly used values across the codebase
"""

# Buffer and Queue Sizes
DEFAULT_BUFFER_SIZE_LARGE = 1000
DEFAULT_BUFFER_SIZE_MEDIUM = 100
DEFAULT_BUFFER_SIZE_SMALL = 50
DEFAULT_EXPERIENCE_BUFFER_SIZE = 20000
DEFAULT_PRIORITY_BUFFER_SIZE = 5000

# Confidence and Thresholds
DEFAULT_CONFIDENCE_THRESHOLD = 0.5
DEFAULT_LOW_THRESHOLD = 0.1
DEFAULT_VERY_LOW_THRESHOLD = 0.01

# Learning and Training
DEFAULT_LEARNING_RATE = 0.001

# Trading Defaults
DEFAULT_VOLUME = 1000
DEFAULT_ACCOUNT_BALANCE = 10000
MNQ_CONTRACT_VALUE = 2000

# Timeout Values (seconds)
DEFAULT_TIMEOUT = 30

# Network Configuration
DEFAULT_TCP_PORT_MAIN = 5556
DEFAULT_TCP_PORT_ALT = 5557

# Emotional/Personality Values
DEFAULT_EMOTIONAL_INTENSITY = 0.7
DEFAULT_PERSONALITY_CONFIDENCE = 0.8

# Volatility Defaults
DEFAULT_VOLATILITY = 0.01
DEFAULT_VOLATILITY_FLOOR = 0.005

# Performance Metrics
DEFAULT_SHARPE_RATIO = 0.0
DEFAULT_WIN_RATE = 0.5
DEFAULT_PROFIT_FACTOR = 1.0
DEFAULT_MAX_DRAWDOWN = 0.0

# Signal Bounds
MAX_DOPAMINE_SIGNAL = 2.0
MIN_DOPAMINE_SIGNAL = -2.0

# Data Quality
MIN_DATA_QUALITY_THRESHOLD = 0.9
MIN_BARS_PER_TIMEFRAME = 10
MIN_CONSECUTIVE_BARS = 5